config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :events do
    member do
      post 'attend', to: 'invitations#create'
      delete 'unattend', to: 'invitations#destroy'
    end
  end

  resources :users

  get 'sessions/new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations, source: :attendee
  validates :title, presence: true, length: { minimum: 5 }

  scope :upcoming, -> { where('date >= ?', Time.zone.now) }
  scope :previous, -> { where('date < ?', Time.zone.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
  belongs_to :attended_event, class_name: 'Event', foreign_key: :attended_event_id

  validates :attended_event_id, uniqueness: { case_sensitive: false, scope: :attendee_id,
                                              message: 'You can only atend once (Matrix! Perhaps!?)' }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id
  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations, source: :attended_event
  validates :name, presence: true, length: { minimum: 4, maximum: 20 }
  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, format: { with: EMAIL_FORMAT }, uniqueness: true

  before_save { self.email = email.downcase }
  # has_secure_password

  def attending?(event)
    attended_events.include?(event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def signed_in_only!
    redirect_to login_path unless current_user
  end

  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper

  before_action :set_event, only: %i[show edit destroy update]
  before_action :signed_in_only!, only: [:index]

  # GET /events
  # GET /events.json
  def index
    @upcoming_events = Event.upcoming
    @prev_events = Event.previous
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
    # @current_inv = current_user.invitations.find_by(attended_event_id: @event.id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)
    respond_to do |format|
      if @event.save && !current_user.nil?
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params) && !current_user.nil?
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.fetch(:event).permit(:title, :description, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  include UsersHelper

  def create
    @event = Event.find(params[:id])
    @attended_event = @event.invitations.create(attendee: current_user)
    # current_user.attended_events << @event
    if @attended_event.save
      redirect_to events_path, notice: 'Thanks for following'
    else
      redirect_to events_path, alert: 'You can only attend once (Matrix! Perhaps!?)'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    # @attended_event = @event.invitations.create(attendee: current_user)
    current_user.attended_events.destroy(@event)
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Invitation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user # && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash.now[:danger] = 'Bad email. Try again.'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @events_by_current_user = current_user.events
    @upcoming_events = @user.attended_events.upcoming
    @prev_events = @user.attended_events.previous
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json

  def create
    @user = User.new(user_params)
    @user.save
    flash[:notice] = 'User created, make your login'
    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def delete(event)
    return unless current_user.id == event.creator_id

    link_to 'Delete', event,
            method: :delete,
            class: 'button is-primary has-text-white'
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
  def event_attendance_button(event)
    if current_user.attending?(event)
      link_to 'Leave', unattend_event_path(event.id), method: :delete, class: 'button is-primary has-text-white'
    else
      link_to 'Join', attend_event_path(event.id), method: :post, class: 'button is-primary has-text-white'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
  <div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
          <tr class="">
            <td class="column">Event: <%= link_to event.title, event %></td>
            <td class="column"><div class="description">Description: <%= event.description %><div></td>
            <td class="column">Date: <%= event.date.to_formatted_s(:long_ordinal)  %></td>
            <td class="column">Creator: <%= event.creator.name %></td>
            <td class="column "><%= delete(event) %></td>
            <td class="column "><%= event_attendance_button(event) %></td>
          </tr>
        </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div class="box box-radius has-background-danger has-text-white new-event-error">
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="box box-radius new-event">
    <div class="field">
      <p>
        <%= form.label :title %>
      </p>
      <p>
        <%= form.text_field :title, class:'input is-info', placeholder:'Title...' %>
      </p>
    </div>

    <div class="field">
      <p>
        <%= form.label :description %>
      </p>
      <p>
        <%= form.text_area :description, class:'textarea is-info', placeholder:'Create new event...' %>
      </p>
    </div>

    <div class="field">
      <p>
        <%= form.label :date %>
      </p>
      <p>
        <%= form.datetime_select :date %>
      </p>
    </div>

    <div >
       <%= form.submit 'Submit', class:"button is-info is-info " %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="controls">
  <%= link_to 'Back', events_path, class:'button is-info' %>
</div>


<%= render 'form', event: @event %>

app/views/events/index.html.erb
  <div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <h1 class="title title-event is-4 navbar-item is-capitalized">Here is a list of our events.</h1>

        <div class="event-tables tables">
          <table>
            <thead>
              <tr>
                <th>
                  <span>Upcoming Events</span>
                </th>
              </tr>
            </thead>

            <tbody>
              <%= render @upcoming_events %>
            </tbody>
        </table>

          <table>

            <thead>
              <tr>
                <th>
                  <span>Previous Events</span>
                </th>
              </tr>
            </thead>

            <tbody>
              <%= render @prev_events %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="controls">
  <%= link_to 'Back', root_path, class:'button is-info' %>
</div>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<div class="controls">
  <%= link_to 'Edit', edit_event_path(@event), class:'button is-primary' %>
  <%= link_to 'Back', events_path, class:'button is-primary' %>
</div>
<div class="single-event-page box box-radius">
  <div >
    <p>
      <strong>Title: </strong>
      <%= @event.title %>
    </p>

    <p>
      <strong>Description: </strong>
      <%= @event.description %>
    </p>

    <p>
      <strong>Date: </strong>
      <%= @event.date.to_formatted_s(:long_ordinal) %>
    </p>

    <p>
      <strong>Creator: </strong>
      <%= @event.creator.name %>
    </p>
  </div>

  <div class="event-btn" style="margin: 10px 0">
    <%= event_attendance_button(@event) %>
  </div>

  <div class="event-attendees">
    <p>
      <strong>Attendees:</strong>
      <% @attendees.each do |attendee| %>
        <li><%= attendee.name %></li>
      <% end %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/0c2dafdccb.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  </head>

  <body>
    <header>
      <% if flash[:notice] %>
        <div class="notification is-primary global-notification is-marginless">
          <h1 class="notice has-text-weight-bold is-family-code"><%= notice %></h1>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="notification is-danger global-notification is-marginless">
          <h1 class="alert has-text-weight-bold is-family-code"><%= alert %></h1>
        </div>
      <% end %>
      <%= render 'shared/nav_bar' %>
      <% if !current_user %>
        <h1 class="title is-4 navbar-item is-marginless">Welcome aboard!</h1>
      <% end %>
    </header>
    <% if current_user %>
      <h1 class="title is-4 navbar-item is-capitalized">Hi <%= current_user.name %>!</h1>
    <% end %>

  <%= yield %>

      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/0c2dafdccb.js" crossorigin="anonymous"></script>
 

  </body>
</html>

app/views/shared/_nav_bar.html.erb
<div class="has-shadow ">
  <nav class="navbar Secondary">
    <% if current_user %>
      <div class="nav-start">

        <strong><%= link_to 'Home', root_path, class:'navbar-item' %></strong>
        <strong><%= link_to 'Users', users_path, class:'navbar-item' %></strong>
        <strong><%= link_to 'All Events', root_path, class:'navbar-item' %></strong>
        <strong><%= link_to current_user.name.capitalize, user_path(current_user), class:'navbar-item' %></strong>
      </div>
      <div class="nav-end">
        <strong><%= link_to 'New Event', new_event_path, class:'button is-info' %></strong>
        <strong><%= link_to 'Log out', logout_path, method: :delete, class:'button is-info' %></strong>
      </div>
    <% end %>

    <% if !current_user %>
      <div class="nav-start">

      </div>
      <div class="nav-end">
        <strong><%= link_to 'Log in', login_path, class:'button is-info' %></strong>
        <strong><%= link_to 'Sign up', new_user_path, class:'button is-info' %></strong>
      </div>
    <% end %>
  </nav>
</div>

app/views/users/_form.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
        <%= form_with(model: user, local: true) do |form| %>
          <% if user.errors.any? %>
            <div class="box box-radius has-background-danger has-text-white">
              <div id="error_explanation">
                <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
                <ul>
                  <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
          <div class="actions">
            <div class="field">
              <%= form.label :name, class:'label' %>
              <div class="control">
                <%= form.text_field :name, class:'input is-border border-info' %>
              </div>
              <%= form.label :email, class:'label mt-5' %>
              <div class="control ">
                <%= form.email_field :email, class:'input border border-info mb-5'  %>
              </div>
              <%= form.submit 'Submit', class:"button is-info is-info " %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <tr class="box box-radius">
          <td class="column">Event: <%= link_to event.title, event %></td>
          <td class="column"><div class="description">Description: <%= event.description %><div></td>
          <td class="column">Date: <%= event.date.to_formatted_s(:long_ordinal)  %></td>
          <td class="column">Creator: <%= event.creator.name %></td>
          <td class="column"><%= delete(event) %></td>
        </tr>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
      <h1 class="title title-event is-4 navbar-item">Here is a list of all the users</h1>
        <div class="event-tables tables">
          <table>
              <tbody>
              <% @users.each do |user| %>
              <tr class="box ">
              <td class="column">User: <%=  user.name %></td>
              <td class="column">Email: <%= user.email %></td>
              </tr>
              <% end %>
              </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
        <h1 class="title title-event is-10 navbar-item is-capitalized is-marginless" style="padding-left: 0">New User</h1>
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
      <div class="event-tables tables">
        <h1 class="title title-event is-4 navbar-item"><%= @user.name.capitalize %>'s events:</h1>
        <table>
          <thead>
            <tr>
              <th>
          </thead>

          <tbody>
            <%= render @events_by_current_user %>
          </tbody>
        </table>
      </div>

      <div class="event-tables tables">
        <h1 class="title title-event is-4 navbar-item"><%= @user.name.capitalize %> is attending the following events:</h1>
        <table>
          <thead>
            <tr>
              <th>
                <span class="text-secondary ">Upcoming Events</span>
              </th>
            </tr>
          </thead>

          <tbody>
            <%= render @upcoming_events %>
          </tbody>
      </table>

        <table>
          <thead>
            <tr>
              <th>
                <span class="text-secondary">Previous Events</span>
              </th>
            </tr>
          </thead>

          <tbody>
            <%= render @prev_events %>
          </tbody>
        </table>
      </div>

     </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
      <div class="controls">
        <%= link_to 'Back', users_path, class:'button is-info' %>
      </div>
     </div>
    </div>
  </div>
</div>